### ISSUE TITLE
CMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by loriab** [LecrisUT/CMake-Template#11]
I've seen with Ninja (single config) + Windows that it uses Debug instead of allowing the project CMake to default to Release. An undesirable solution is to set (w/cache) _above_ `project()`.

```
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Choose the type of build.")  # foil Ninja Debug on Windows

project(
```

**Comment by LecrisUT** [comment]
Ok, I have confirmed that the position of `CMAKE_BUILD_TYPE` does matter and it should be above `project()` in this case. It seems it is fine to have it as a normal variable:
- set after project: `/Od` [^1]
- set before project: `/O2` [^2]

Looking more closely, it seems that `CMAKE_BUILD_TYPE` is populated by default if nothing is passed:
```
//Choose the type of build, options are: None Debug Release RelWithDebInfo
// MinSizeRel ...
CMAKE_BUILD_TYPE:STRING=Debug
```
But it still works with :shrug:.
```cmake
if (NOT CMAKE_BUILD_TYPE)
	set(CMAKE_BUILD_TYPE Release)
endif ()
```
It seems like a bug somewhere since in the other cases the cache variable is:
```
//Choose the type of build, options are: None Debug Release RelWithDebInfo
// MinSizeRel ...
CMAKE_BUILD_TYPE:STRING=
```

[^1]: https://github.com/LecrisUT/CMake-Template/actions/runs/8046900183/job/21975104826
[^2]: https://github.com/LecrisUT/CMake-Template/actions/runs/8047422750/job/21976647512
